"""
PDF Report Generation using FPDF2
"""
from fpdf import FPDF
import os
from datetime import datetime
from typing import Optional


class MedicalReportPDF(FPDF):
    """Custom PDF class for medical reports"""
    
    def header(self):
        # Header with title
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Ashwini Radiology Intelligence System', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'AI-Powered Medical Image Analysis Report', 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        # Footer with page number
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
        self.cell(0, 10, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 0, 'R')
    
    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, title, 0, 1, 'L', 1)
        self.ln(4)
    
    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 5, body)
        self.ln()


def generate_pdf_report(
    prediction: str,
    confidence: float,
    severity_score: float,
    modality: str,
    uncertainty_std: float,
    is_uncertain: bool,
    exact_point: dict,
    gemini_summary: str,
    heatmap_path: str,
    output_path: str
) -> str:
    """
    Generate comprehensive PDF report
    
    Args:
        prediction: Predicted class
        confidence: Confidence score (0-1)
        severity_score: Severity score (1-10)
        modality: Imaging modality
        uncertainty_std: Uncertainty standard deviation
        is_uncertain: Whether prediction is uncertain
        exact_point: Dictionary with x, y coordinates
        gemini_summary: AI-generated clinical narrative
        heatmap_path: Path to GradCAM heatmap image
        output_path: Output path for PDF
    
    Returns:
        Output path of the generated PDF
    """
    pdf = MedicalReportPDF()
    pdf.add_page()
    
    # Patient Information Section
    pdf.chapter_title('Analysis Summary')
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 6, f'Modality: {modality}', 0, 1)
    pdf.cell(0, 6, f'Prediction: {prediction}', 0, 1)
    pdf.cell(0, 6, f'Confidence: {confidence:.2%}', 0, 1)
    pdf.cell(0, 6, f'Severity Score: {severity_score:.1f}/10.0', 0, 1)
    pdf.cell(0, 6, f'Uncertainty (Std Dev): {uncertainty_std:.4f}', 0, 1)
    
    # Uncertainty flag
    if is_uncertain:
        pdf.set_text_color(255, 0, 0)
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 6, '⚠ HIGH UNCERTAINTY - Review Recommended', 0, 1)
        pdf.set_text_color(0, 0, 0)
    
    pdf.ln(5)
    
    # Exact Point Coordinates
    pdf.chapter_title('Localization')
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 6, f'Exact Point of Maximum Activation:', 0, 1)
    pdf.cell(0, 6, f'  X: {exact_point.get("x", "N/A")}, Y: {exact_point.get("y", "N/A")}', 0, 1)
    pdf.ln(5)
    
    # Heatmap Image
    if os.path.exists(heatmap_path):
        pdf.chapter_title('Grad-CAM Heatmap')
        try:
            # Add image centered, max width 150mm
            pdf.image(heatmap_path, x=30, w=150)
            pdf.ln(10)
        except Exception as e:
            pdf.cell(0, 6, f'Heatmap image not available: {str(e)}', 0, 1)
            pdf.ln(5)
    
    # AI Clinical Narrative
    pdf.chapter_title('AI Clinical Narrative (Gemini)')
    pdf.set_font('Arial', 'I', 9)
    pdf.cell(0, 6, 'The following summary was generated by Google Gemini 1.5 Flash:', 0, 1)
    pdf.ln(2)
    pdf.set_font('Arial', '', 10)
    
    # Clean and format Gemini summary
    cleaned_summary = gemini_summary.strip()
    pdf.multi_cell(0, 5, cleaned_summary)
    pdf.ln(5)
    
    # Disclaimer
    pdf.add_page()
    pdf.chapter_title('Disclaimer')
    pdf.set_font('Arial', '', 10)
    disclaimer = (
        "This report is generated by an AI system and should be used as a decision "
        "support tool only. All findings must be verified by qualified medical professionals. "
        "This system is not intended to replace clinical judgment or provide definitive diagnoses."
    )
    pdf.multi_cell(0, 5, disclaimer)
    
    # Save PDF
    pdf.output(output_path)
    return output_path
